# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  go-server
  labels:
    app:  go-server
spec:
  selector:
    matchLabels:
      app: go-server
  replicas: 3
  template:
    metadata:
      labels:
        app:  go-server
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name:  go-server
        image:  go-server:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
          name:  go-server
---
